### ISSUE TITLE
Can't download the zip

### ISSUE THREAD

**Issue by V4NDL0** [LucaBarile/AntiAlexa#1]
The zip file is blocked/broken in Chrome and Edge "This site cannot be reached". I cannot find a way to download it

**Comment by LucaBarile** [comment]
It's working fine for me (I've tried with Firefox) 🤔
Have you tried to directly download the executable file from [here](https://github.com/LucaBarile/AntiAlexa/raw/main/AntiAlexa/AntiAlexa/bin/Debug/AntiAlexa.exe)?

Anyhow, I've attached the zip file to you.
[AntiAlexa-main.zip](https://github.com/LucaBarile/AntiAlexa/files/8700212/AntiAlexa-main.zip)
